version: '2.1'
services:
  zookeeper:
    image: quay.io/debezium/zookeeper:1.8
    container_name: zookeeper
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    networks:
     - my-network
  kafka:
    image: quay.io/debezium/kafka:1.8
    container_name: kafka
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
    networks:
     - my-network 

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql
    ports:
     - 1433:1433
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_PID=Standard
     - SA_PASSWORD=Password!
     - MSSQL_AGENT_ENABLED=true
    networks:
     - my-network 
     
  connect:
    image: quay.io/debezium/connect:1.8
    container_name: connect
    ports:
     - 8083:8083
     - 5005:5005
    links:
     - kafka
     - sqlserver
    
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
     - KAFKA_DEBUG=true
     - DEBUG_SUSPEND_FLAG=n
    networks:
     - my-network

      
networks:
  my-network:
    name: cloudevents-network